version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-iot
    ports:
      - "1883:1883" # MQTT port
    volumes:
      - /home/xiaoye/mosquitto/config:/mosquitto/config # Your Mosquitto configuration file
      - /home/xiaoye/mosquitto/mosquitto/data:/mosquitto/data # Persistent data volume for Mosquitto
      - /home/xiaoye/mosquitto/mosquitto/log:/mosquitto/log # Log volume
    restart: unless-stopped
    networks:
      - mqtt-network

  paho_mqtt:
    build: ./paho_mqtt  # Directory containing Dockerfile and paho_mqtt.py
    container_name: paho_mqtt_runner
    depends_on:
      - mosquitto
    networks:
      - mqtt-network
    restart: unless-stopped

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    container_name: zigbee2mqtt-iot
    ports:
      - "8080:8080"
    volumes:
      - /home/xiaoye/zigbee2mqtt/data:/app/data # Persistent data volume for Zigbee2MQTT
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0 # Replace with your Zigbee dongle's device path
    environment:
      - MQTT_SERVER=mosquitto
      - MQTT_PORT=1883
      - TZ=Asia/Singapore
    restart: unless-stopped
    depends_on:
      - mosquitto
    networks:
      - mqtt-network

  # homeassistant:
  #   container_name: home-assistant
  #   image: homeassistant/raspberrypi4-homeassistant:stable
  #   ports:
  #     - "8123:8123"
  #   volumes:
  #     - /home/xiaoye/home-assistant/config:/config
  #   environment:
  #     - TZ=Asia/Singapore
  #   network_mode: host
  #   depends_on:
  #     - zigbee2mqtt
  #   restart: always

networks:
  mqtt-network:
    driver: bridge
